@startuml

package  anoncreds.repo {

interface PublicRepo
interface AttributesRepo
interface LocalRepo
interface IssuerLocalRepo
interface ProverLocalRepo

class PublicRepoInMemory
class LocalRepoInMemory
class IssuerLocalRepoInMemory
class ProverLocalRepoInMemory
class AttributesRepoInMemory

AttributesRepo <|-- AttributesRepoInMemory
PublicRepo <|-- PublicRepoInMemory

LocalRepo <|-- IssuerLocalRepo
LocalRepo <|-- ProverLocalRepo

LocalRepo <|-- LocalRepoInMemory
LocalRepoInMemory <|-- IssuerLocalRepoInMemory
LocalRepoInMemory <|-- ProverLocalRepoInMemory

IssuerLocalRepo <|-- IssuerLocalRepoInMemory
ProverLocalRepo <|-- ProverLocalRepoInMemory
}


package  anoncreds.wallet {

class Wallet
class Wallet <|-- IssuerWallet
class Wallet <|-- ProverWallet

Wallet o-- PublicRepo
Wallet o-- LocalRepo

IssuerWallet o-- IssuerLocalRepo
ProverWallet o-- ProverLocalRepo
}


package  anoncreds {

class Issuer
class Prover
class Verifier

Issuer o-- IssuerWallet
Issuer o-- AttributesRepo
Prover o-- ProverWallet
Verifier o-- Wallet
}

@enduml