#!/bin/bash

# disabling auto update for indy-anoncreds package
apt-mark hold indy-anoncreds

# Automatically added from template:
if which py3compile >/dev/null 2>&1; then
	py3compile -O -p indy-anoncreds /usr/local/lib/python3.5/dist-packages/
fi

# End automatically added section
